task:
  class: SequenceClassificationTask
  mode: train
  label_name: 'label'
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: roberta-base
  data:
    train:
      class: InMemoryDataLoader
      dataset:
        class: ParallelTextDataset
        sort_samples: True
        path:
          input0: examples/sequence_classification/glue/data/CoLA/train.input0
          label: examples/sequence_classification/glue/data/CoLA/train.label
      sampler:
        class: ShuffleSampler
        max_samples: 16
    dev:
      class: InMemoryDataLoader
      dataset:
        class: ParallelTextDataset
        sort_samples: True
        path:
          input0: examples/sequence_classification/glue/data/CoLA/dev.input0
          label: examples/sequence_classification/glue/data/CoLA/dev.label
      sampler:
        class: SequentialSampler
        max_samples: 16
  model:
    class: HuggingfaceSequenceClassificationModel
    pretrained_model: roberta-base
  criterion:
    class: CrossEntropy
  trainer:
    class: AdvTrainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 1e-5
        warmup_steps: 320
        total_steps: 5336
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_steps: 5336
    validate_interval_epoch: 1
  generator:
    class: Generator
  evaluator:
    class: Evaluator
    metric:
      matthews_corr:
        class: MatthewsCorr
env:
  device: cuda