task:
  class: SequenceClassificationTask
  mode: train
  label_name: 'label'
  maxlen: 128
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: roberta-base
  data:
    train:
      class: InMemoryDataLoader
      dataset:
        class: ParallelTextDataset
        sort_samples: True
        path:
          input0: examples/sequence_classification/glue/data/QNLI/train.input0
          input1: examples/sequence_classification/glue/data/QNLI/train.input1
          label: examples/sequence_classification/glue/data/QNLI/train.label
      sampler:
        class: ShuffleSampler
        max_samples: 32
    dev:
      class: InMemoryDataLoader
      dataset:
        class: ParallelTextDataset
        sort_samples: True
        path:
          input0: examples/sequence_classification/glue/data/QNLI/dev.input0
          input1: examples/sequence_classification/glue/data/QNLI/dev.input1
          label: examples/sequence_classification/glue/data/QNLI/dev.label
      sampler:
        class: SequentialSampler
        max_samples: 32
  model:
    class: HuggingfaceSequenceClassificationModel
    pretrained_model: roberta-base
  criterion:
    class: CrossEntropy
  trainer:
    class: AdvTrainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 1e-5
        warmup_steps: 1986
        total_steps: 33112
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_steps: 33112
    validate_interval_epoch: 1
  generator:
    class: Generator
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
env:
  device: cuda