task:
  class: SequenceClassificationTask
  mode: train
  label_name: 'label'
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: bert-base-uncased
  data:
    train:
      class: InMemoryDataLoader
      dataset:
        class: ParallelTextDataset
        sort_samples: True
        path:
          input0: glue/data/SST-2/train.input0
          label: glue/data/SST-2/train.label
      sampler:
        class: ShuffleSampler
        max_samples: 32
    dev:
      class: InMemoryDataLoader
      dataset:
        class: ParallelTextDataset
        sort_samples: True
        path:
          input0: glue/data/SST-2/dev.input0
          label: glue/data/SST-2/dev.label
      sampler:
        class: SequentialSampler
        max_samples: 32
  model:
    class: AdvHuggingfaceSequenceClassificationModel
    pretrained_model: bert-base-uncased
  criterion:
    class: CrossEntropy
  trainer:
    class: AdvTrainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 1e-5
        warmup_steps: 1256
        total_steps: 20935
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_steps: 20935
    validate_interval_epoch: 1
  generator:
    class: Generator
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
env:
  device: cuda:0