task:
  class: GLATTranslationTask
  mode: evaluate
  src: en
  tgt: de
  maxlen: 256
  index_only: True
  share_vocab: False
  post_detok: False
  tokenizer:
    en:
      class: FastBPE
      vocab: data/dict.en.txt
      add_bos: True
      add_eos: True
    de:
      class: FastBPE
      vocab: data/dict.de.txt
      add_bos: True
      add_eos: True
  dataloader:
    test:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    test:
      class: ParallelTextDataset
      sort_samples: True
      path:
        de: data/test.en-de.de
        en: data/test.en-de.en
  model:
    class: GLATModel
    encoder:
      class: TransformerEncoder
      num_layers: 6
      d_model: 512
      n_head: 8
      dim_feedforward: 2048
      dropout: 0.1
      attention_dropout: 0.1
      activation: 'gelu'
      return_seed: True
      learn_pos: True
      embed_scale: False
      embed_layer_norm: True
    decoder:
      class: NonAutoTransformerDecoder
      num_layers: 6
      d_model: 512
      n_head: 8
      dim_feedforward: 2048
      dropout: 0.1
      attention_dropout: 0.1
      activation: 'gelu'
      learn_pos: True
      embed_layer_norm: True
    d_model: 512
    max_output_length: 256
    share_embedding: decoder-input-output
    decoder_input: unk
    path: checkpoint/last_avg.pt
  generator:
    class: GLATGenerator
    search:
      class: GLATLengthSearcher
      beam: 7
  evaluator:
    class: Evaluator
    metric:
      bleu:
        class: BLEU
        no_tok: True
env:
  device: cuda
  fp16: True
  no_progress_bar: True
  no_warning: True
