task:
  class: SequenceClassificationTask
  mode: train
  label_name: 'label'
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: roberta-base
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 16
    dev:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 128
  data:
    train:
      class: ParallelTextDataset
      sort_samples: True
      path:
        input0: data/CoLA/train.input0
        label: data/CoLA/train.label
    dev:
      class: ParallelTextDataset
      sort_samples: True
      path:
        input0: data/CoLA/dev.input0
        label: data/CoLA/dev.label
  model:
    class: HuggingfaceSequenceClassificationModel
    pretrained_model: roberta-base
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 2e-5
        warmup_steps: 320
        total_steps: 5336
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_steps: 5336
    validate_interval_epoch: 1
    assess_by: matthews_corr
  generator:
    class: Generator
  evaluator:
    class: Evaluator
    metric:
      matthews_corr:
        class: MatthewsCorr
env:
  device: cuda
