task:
  class: SequenceClassificationTask
  mode: train
  label_name: 'label'
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: roberta-base
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 16
    dev_matched:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 16
    dev_mismatched:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 16
  data:
    train:
      class: ParallelTextDataset
      sort_samples: True
      path:
        input0: data/MNLI/train.input0
        input1: data/MNLI/train.input1
        label: data/MNLI/train.label
    dev_matched:
      class: ParallelTextDataset
      sort_samples: True
      path:
        input0: data/MNLI/dev_matched.input0
        input1: data/MNLI/dev_matched.input1
        label: data/MNLI/dev_matched.label
    dev_mismatched:
      class: ParallelTextDataset
      sort_samples: True
      path:
        input0: data/MNLI/dev_mismatched.input0
        input1: data/MNLI/dev_mismatched.input1
        label: data/MNLI/dev_mismatched.label
  model:
    class: HuggingfaceSequenceClassificationModel
    pretrained_model: roberta-base
    num_labels: 3
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 1e-5
        warmup_steps: 7432
        total_steps: 123873
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_steps: 123873
    validate_interval_epoch: 1
    assess_by: acc
  generator:
    class: Generator
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
env:
  device: cuda
