task:
  class: SequenceClassificationTask
  mode: train
  label_name: 'label'
  maxlen: 128
  tokenizer:
    class: HuggingfaceTokenizer
    tokenizer_name: roberta-base
  dataloader:
    train:
      class: InMemoryDataLoader
      sampler:
        class: ShuffleSampler
        max_samples: 32
    dev:
      class: InMemoryDataLoader
      sampler:
        class: SequentialSampler
        max_samples: 32
  data:
    train:
      class: ParallelTextDataset
      sort_samples: True
      path:
        input0: data/QNLI/train.input0
        input1: data/QNLI/train.input1
        label: data/QNLI/train.label
    dev:
      class: ParallelTextDataset
      sort_samples: True
      path:
        input0: data/QNLI/dev.input0
        input1: data/QNLI/dev.input1
        label: data/QNLI/dev.label
  model:
    class: HuggingfaceSequenceClassificationModel
    pretrained_model: roberta-base
  criterion:
    class: CrossEntropy
  trainer:
    class: Trainer
    optimizer:
      class: AdamW
      lr:
        class: PolynomialDecayScheduler
        max_rate: 1e-5
        warmup_steps: 1986
        total_steps: 33112
      betas: (0.9, 0.98)
      weight_decay: 0.01
      eps: 1e-6
    max_steps: 33112
    validate_interval_epoch: 1
    assess_by: acc
  generator:
    class: Generator
  evaluator:
    class: Evaluator
    metric:
      acc:
        class: Accuracy
env:
  device: cuda
